// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  liaoSidebar: [{type: 'autogenerated', dirName: 'liao'}],
  chenSidebar: [{type: 'autogenerated', dirName: 'chen'}],
  childrenSidebar: [{type: 'autogenerated', dirName: 'children'}],
  classicPoetrySidebar: [{type: 'autogenerated', dirName: 'poetry/classic'}],
  modernPoetrySidebar: [{type: 'autogenerated', dirName: 'poetry/modern'}],
};

module.exports = sidebars;
